#SERIAL_DRIVER = vendor
POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = pmw3360
TAP_DANCE_ENABLE = yes
MOUSE_SHARED_EP = yes
# SPLIT_KEYBOARD = yes
# RGB_MATRIX_ENABLE = yes
# RGB_MATRIX_DRIVER = ws2812
